# Generated by Django 6.0.3 on 2026-04-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectphase_unique_id_site_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'En planification'), ('ACTIVE', 'Actif'), ('PAUSED', 'En pause'), ('COMPLETED', 'Complété'), ('CANCELLED', 'Annulé')], default='PLANNING', max_length=20),
        ),
    ]
