# Generated by Django 5.2.17 on 2026-09-21 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_site_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectphase",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectphase",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="phases_closed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Clôturée par",
            ),
        ),
        migrations.AddField(
            model_name="projectphase",
            name="closure_notes",
            field=models.TextField(blank=True, verbose_name="Notes de clôture"),
        ),
        migrations.AddField(
            model_name="projectphase",
            name="status",
            field=models.CharField(
                choices=[("EN_COURS", "En cours"), ("CLOTUREE", "Clôturée")],
                default="EN_COURS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="lead_engineer",
            field=models.ForeignKey(
                blank=True,
                help_text="Ingénieur responsable de ce chantier — clôture les étapes et examine la planification.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites_led",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ingénieur principal",
            ),
        ),
        migrations.CreateModel(
            name="PlanningSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de la planification"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("SOUMISE", "Soumise"),
                            ("APPROUVEE", "Approuvée"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Notes de revue"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        help_text="Étape concernée (facultatif)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_submissions",
                        to="projects.projectphase",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_submissions_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_submissions",
                        to="projects.site",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_submissions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Planification soumise",
                "verbose_name_plural": "Planifications soumises",
                "ordering": ["-created_at"],
            },
        ),
    ]
