# Generated by Django 5.2.17 on 2026-10-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_progressphoto_progresscomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="contract_mode",
            field=models.CharField(
                choices=[
                    ("CLE_EN_MAIN", "Clé en main (travaux + matériaux)"),
                    (
                        "MAIN_OEUVRE_SEULEMENT",
                        "Main d'œuvre seulement (client achète les matériaux)",
                    ),
                    ("LIVRAISON_ETAPES", "Livraison étape par étape"),
                    ("SUIVI_SEULEMENT", "Suivi de chantier seulement"),
                ],
                default="CLE_EN_MAIN",
                help_text="Type de contrat signé avec le client — pré-établi dès la création du chantier, modifiable plus tard par un directeur si l'accord avec le client change. Détermine quelles fonctionnalités (feuilles) sont pertinentes pour ce chantier : voir get_enabled_modules().",
                max_length=30,
                verbose_name="Type de contrat",
            ),
        ),
    ]
