# Generated by Django 5.2.17 on 2026-10-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_site_contract_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectphase",
            name="parent_phase",
            field=models.ForeignKey(
                blank=True,
                help_text="Laisser vide pour une étape principale. Sélectionner une étape existante en fait une sous-étape de celle-ci (un seul niveau de profondeur — une sous-étape ne peut pas elle-même avoir de sous-étapes).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_phases",
                to="projects.projectphase",
                verbose_name="Étape parente",
            ),
        ),
    ]
