# Generated by Django 5.2.17 on 2026-10-08 14:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_projectphase_parent_phase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="basement_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Niveaux en sous-sol (parking, cave...) — 0 si aucun.",
                verbose_name="Nombre de sous-sols",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="floor_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 = rez-de-chaussée seul ; 1 = R+1 ; 2 = R+2, etc. Détermine combien de niveaux apparaissent dans l'onglet Structure (voir sync_levels()) — un niveau par étage, en plus du RDC et des sous-sols éventuels.",
                verbose_name="Nombre d'étages (R+N)",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="footprint_area_m2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Surface au sol occupée par le bâtiment. Sert de valeur par défaut pour la surface plancher (floor_area_m2) de chaque niveau dont ce champ est laissé vide — un étage dont l'emprise diffère réellement (retrait, porte-à-faux, extension) peut la renseigner lui-même pour remplacer ce défaut.",
                max_digits=8,
                null=True,
                verbose_name="Emprise au sol (m²)",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="structure_type",
            field=models.CharField(
                choices=[
                    ("POTEAUX_POUTRES", "Poteaux-poutres (béton armé)"),
                    ("MACONNERIE_PORTANTE", "Maçonnerie portante"),
                    ("MIXTE", "Mixte"),
                ],
                default="POTEAUX_POUTRES",
                help_text="Indicatif pour la saisie des niveaux — ne bloque aucun champ. Poteaux-poutres : chaque niveau a sa propre trame de poutres/colonnes. Maçonnerie portante : les murs porteurs reprennent les charges, les champs poutres/colonnes restent disponibles mais sont généralement laissés à 0.",
                max_length=20,
                verbose_name="Type de structure",
            ),
        ),
        migrations.CreateModel(
            name="SiteLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "level_index",
                    models.SmallIntegerField(
                        help_text="0 = RDC, 1..N = R+1..R+N, négatif = sous-sol. Géré par Site.sync_levels().",
                        verbose_name="Indice de niveau",
                    ),
                ),
                (
                    "height_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Hauteur sous plafond (m)",
                    ),
                ),
                (
                    "floor_area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Laisser vide pour reprendre l'emprise au sol du chantier (voir Site.footprint_area_m2).",
                        max_digits=8,
                        null=True,
                        verbose_name="Surface plancher (m²)",
                    ),
                ),
                (
                    "wall_length_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Périmètre extérieur + refends (murs de séparation intérieurs) de ce niveau.",
                        max_digits=8,
                        null=True,
                        verbose_name="Longueur cumulée des murs (m)",
                    ),
                ),
                (
                    "opening_area_m2",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Portes et fenêtres de ce niveau — déduite de la surface des murs pour une estimation plus juste des parpaings/enduit (voir wall_area_m2).",
                        max_digits=6,
                        verbose_name="Surface des ouvertures (m²)",
                    ),
                ),
                (
                    "beam_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de poutres"
                    ),
                ),
                (
                    "beam_section_width_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.20"),
                        max_digits=4,
                        null=True,
                        verbose_name="Section des poutres — largeur (m)",
                    ),
                ),
                (
                    "beam_section_height_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.40"),
                        max_digits=4,
                        null=True,
                        verbose_name="Section des poutres — hauteur (m)",
                    ),
                ),
                (
                    "beam_total_length_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Somme des portées de toutes les poutres de ce niveau (pas la longueur d'une seule).",
                        max_digits=8,
                        null=True,
                        verbose_name="Longueur totale des poutres (m)",
                    ),
                ),
                (
                    "column_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de colonnes"
                    ),
                ),
                (
                    "column_section_width_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.20"),
                        max_digits=4,
                        null=True,
                        verbose_name="Section des colonnes — largeur (m)",
                    ),
                ),
                (
                    "column_section_depth_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.20"),
                        max_digits=4,
                        null=True,
                        verbose_name="Section des colonnes — profondeur (m)",
                    ),
                ),
                (
                    "slab_thickness_m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.15"),
                        help_text="Dalle haute de ce niveau (plancher de l'étage suivant, ou toiture-terrasse pour le dernier niveau).",
                        max_digits=4,
                        null=True,
                        verbose_name="Épaisseur de la dalle (m)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="projects.site",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau de chantier",
                "verbose_name_plural": "Niveaux de chantier",
                "ordering": ["level_index"],
                "unique_together": {("site", "level_index")},
            },
        ),
    ]
