# Generated by Django 5.2.17 on 2026-10-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_site_basement_count_site_floor_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitelevel",
            name="opening_area_m2",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Portes et fenêtres de ce niveau — déduite de la surface des murs pour une estimation plus juste des parpaings/enduit (voir wall_area_m2).",
                max_digits=6,
                null=True,
                verbose_name="Surface des ouvertures (m²)",
            ),
        ),
    ]
