# Generated by Django 6.0.3 on 2026-04-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_personnel_unique_id_siteassignment_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='default_daily_rate',
            field=models.DecimalField(decimal_places=2, help_text='Default daily cost', max_digits=10, verbose_name='Default Daily Rate'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='siteassignment',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, help_text='Agreed rate for this specific assignment', max_digits=10, verbose_name='Daily Rate'),
        ),
        migrations.AlterField(
            model_name='siteassignment',
            name='role',
            field=models.CharField(help_text="Specific role on this site, e.g. Chef d'équipe", max_length=100, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Skill Name'),
        ),
    ]
