# Generated by Django 5.2.17 on 2026-09-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0004_alter_personnel_default_daily_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="personnel_type",
            field=models.CharField(
                choices=[
                    ("EMPLOYE", "Employé"),
                    ("TACHERON", "Tâcheron (journalier)"),
                    ("PRESTATAIRE", "Prestataire (sous-traitant)"),
                ],
                default="EMPLOYE",
                help_text="Employé permanent, tâcheron (journalier) ou prestataire (sous-traitant)",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
