# Generated by Django 5.2.17 on 2026-09-21 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_usercabinetrole_role"),
        ("personnel", "0005_personnel_personnel_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="category",
            field=models.CharField(
                choices=[
                    ("TERRAIN", "Agent de terrain"),
                    ("ADMINISTRATION", "Agent d'administration"),
                ],
                default="TERRAIN",
                help_text="Agent de terrain ou d'administration",
                max_length=20,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="monthly_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Salaire mensuel fixe (agents administratifs / ingénieurs). Laisser vide pour un ouvrier payé au journalier.",
                max_digits=10,
                null=True,
                verbose_name="Salaire mensuel",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIF", "Actif"),
                    ("INACTIF", "Inactif"),
                    ("NON_ELIGIBLE", "Non éligible"),
                ],
                default="ACTIF",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="trade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MACON", "Maçon"),
                    ("MENUISIER", "Menuisier"),
                    ("FERRAILLEUR", "Ferrailleur"),
                    ("PLOMBIER", "Plombier"),
                    ("ELECTRICIEN", "Électricien"),
                    ("AJUSTEUR", "Ajusteur"),
                    ("PEINTRE", "Peintre"),
                    ("VITRIER", "Vitrier"),
                    ("CARRELEUR", "Carreleur"),
                    ("CONSULTANT", "Consultant"),
                ],
                help_text="Fonction de l'ouvrier (Maçon, Menuisier, Plombier, ...)",
                max_length=20,
                verbose_name="Fonction / Métier",
            ),
        ),
        migrations.AddField(
            model_name="siteassignment",
            name="agreement_document",
            field=models.FileField(
                blank=True,
                help_text="Convention de main-d'œuvre signée pour cette affectation.",
                null=True,
                upload_to="personnel/agreements/",
                verbose_name="Convention (document)",
            ),
        ),
        migrations.AddField(
            model_name="siteassignment",
            name="agreement_notes",
            field=models.TextField(
                blank=True,
                help_text="Conditions particulières de la convention de main-d'œuvre.",
                verbose_name="Termes de la convention",
            ),
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("CONGE", "Congé"),
                            ("JOUR_FERIE", "Jour férié"),
                            ("MALADIE", "Congé maladie"),
                            ("AUTRE", "Autre"),
                        ],
                        default="CONGE",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                ("reason", models.TextField(blank=True, verbose_name="Motif")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente d'approbation"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="personnel.personnel",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PersonnelDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Ex: Copie CNI, Diplôme, Contrat de travail",
                        max_length=150,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="personnel/documents/", verbose_name="Fichier"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="personnel.personnel",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="accounts.cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("cabinet", "date")},
            },
        ),
    ]
