# Generated by Django 5.2.17 on 2026-09-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0006_personnel_category_personnel_monthly_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="payroll_type",
            field=models.CharField(
                choices=[
                    ("OUVRIER", "Ouvrier (main d'œuvre)"),
                    ("INGENIEUR", "Ingénieur"),
                ],
                default="OUVRIER",
                help_text="Ouvrier (main d'œuvre, payé selon convention par chantier) ou Ingénieur (salarié) — détermine la catégorie de décaissement sur la liste de paie.",
                max_length=20,
                verbose_name="Catégorie de paie",
            ),
        ),
        migrations.AddField(
            model_name="siteassignment",
            name="convention_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant total convenu pour cette tâche (ex : communiqué par l'Archi à la caisse). Laisser vide si aucun plafond n'est suivi. Un même personnel peut avoir plusieurs conventions actives sur un même chantier — une par tâche.",
                max_digits=12,
                null=True,
                verbose_name="Montant de la convention",
            ),
        ),
    ]
