# Generated by Django 5.2.17 on 2026-09-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0007_personnel_payroll_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="payroll_type",
            field=models.CharField(
                choices=[
                    ("OUVRIER", "Ouvrier (main d'œuvre)"),
                    ("INGENIEUR", "Ingénieur / Staff"),
                ],
                default="OUVRIER",
                help_text="Ouvrier (main d'œuvre, payé selon convention par chantier) ou Ingénieur (salarié) — détermine la catégorie de décaissement sur la liste de paie.",
                max_length=20,
                verbose_name="Catégorie de paie",
            ),
        ),
    ]
