# Generated by Django 5.2.17 on 2026-10-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0009_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="default_daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tarif journalier par défaut — optionnel depuis 2026-10-06 : laisser vide pour un personnel payé uniquement par convention (par étape de chantier) plutôt qu'au journalier.",
                max_digits=10,
                null=True,
                verbose_name="Tarif journalier",
            ),
        ),
    ]
