# Generated by Django 5.2.17 on 2026-10-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0010_alter_personnel_default_daily_rate"),
        ("projects", "0005_progressphoto_progresscomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteassignment",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Nom donné à cette convention par celui qui l'enregistre (ex : « Finition dalle bloc B »). Optionnel pour une affectation classique (role/dates/tarif journalier) ; utilisé par la section « Chantiers & conventions » du formulaire Personnel.",
                max_length=150,
                verbose_name="Nom de la convention",
            ),
        ),
        migrations.AddField(
            model_name="siteassignment",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                help_text="L'étape (ProjectPhase) du chantier à laquelle cette convention se rapporte.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conventions",
                to="projects.projectphase",
                verbose_name="Étape du chantier",
            ),
        ),
        migrations.AlterField(
            model_name="siteassignment",
            name="daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Agreed rate for this specific assignment",
                max_digits=10,
                null=True,
                verbose_name="Daily Rate",
            ),
        ),
        migrations.AlterField(
            model_name="siteassignment",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="Specific role on this site, e.g. Chef d'équipe",
                max_length=100,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="siteassignment",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
