# Generated by Django 5.2.17 on 2026-10-07 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0011_siteassignment_name_siteassignment_phase_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="is_chef_de_corps",
            field=models.BooleanField(
                default=False,
                help_text="Sous-traitant qui contracte avec le Cabinet pour tout un corps de métier (plomberie, maçonnerie, électricité, carrelage, ferraillage, charpente, soudure, ...) à une étape donnée, selon une convention négociée avec lui — il rémunère ensuite lui-même ses propres ouvriers, sans l'intervention du Cabinet, sauf en cas de dispute avec eux. Apparaît dans la section « Chefs de corps », distincte de la liste Personnel classique, mais partage le même enregistrement et les mêmes conventions par chantier (SiteAssignment).",
                verbose_name="Chef de corps",
            ),
        ),
        migrations.AddField(
            model_name="siteassignment",
            name="initial_convention_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant de la toute première convention, avant le premier avenant — rempli automatiquement par ConventionAvenant.record() la première fois qu'un avenant est enregistré sur cette convention. Reste vide tant qu'aucun avenant n'a eu lieu : utiliser effective_initial_amount pour lire « la convention initiale, qu'il y ait eu un avenant ou non ».",
                max_digits=12,
                null=True,
                verbose_name="Convention initiale",
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="trade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MACON", "Maçon"),
                    ("MENUISIER", "Menuisier"),
                    ("FERRAILLEUR", "Ferrailleur"),
                    ("PLOMBIER", "Plombier"),
                    ("ELECTRICIEN", "Électricien"),
                    ("AJUSTEUR", "Ajusteur"),
                    ("PEINTRE", "Peintre"),
                    ("VITRIER", "Vitrier"),
                    ("CARRELEUR", "Carreleur"),
                    ("CHARPENTIER", "Charpentier"),
                    ("SOUDEUR", "Soudeur"),
                    ("CONSULTANT", "Consultant"),
                ],
                help_text="Fonction de l'ouvrier (Maçon, Menuisier, Plombier, ...)",
                max_length=20,
                verbose_name="Fonction / Métier",
            ),
        ),
        migrations.AlterField(
            model_name="siteassignment",
            name="convention_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant total convenu pour cette tâche (ex : communiqué par l'Archi à la caisse). Laisser vide si aucun plafond n'est suivi. Un même personnel peut avoir plusieurs conventions actives sur un même chantier — une par tâche. C'est aussi le plafond *actuel* d'une convention de Chef de corps : ConventionAvenant.record() le met à jour à chaque renégociation (voir initial_convention_amount pour le tout premier montant convenu).",
                max_digits=12,
                null=True,
                verbose_name="Montant de la convention",
            ),
        ),
        migrations.CreateModel(
            name="ConventionAvenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date", models.DateField(verbose_name="Date de l'avenant")),
                (
                    "previous_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Ancien montant"
                    ),
                ),
                (
                    "new_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Nouveau montant"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Ex : surplus de travail annoncé par le chef technique, révision de prix des matériaux, retard du chantier...",
                        verbose_name="Motif",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avenants",
                        to="personnel.siteassignment",
                        verbose_name="Convention",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="La caissière (ou le caissier) qui a saisi cet avenant dans le système.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="convention_avenants_recorded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avenant de convention",
                "verbose_name_plural": "Avenants de convention",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
