# Generated by Django 6.0.3 on 2026-04-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', "En attente d'approbation"), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('PAID', 'Payé')], default='PENDING', max_length=20),
        ),
    ]
