# Generated by Django 5.2.17 on 2026-09-21 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_expense_status"),
        ("personnel", "0005_personnel_personnel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="nature",
            field=models.CharField(
                choices=[
                    ("MATERIEL", "Matériel"),
                    ("MAIN_DOEUVRE", "Main d'œuvre"),
                    ("AUTRE", "Autre"),
                ],
                default="MATERIEL",
                help_text="Cette dépense couvre-t-elle un achat de matériel ou de la main d'œuvre ?",
                max_length=20,
                verbose_name="Matériel ou main d'œuvre",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="personnel",
            field=models.ForeignKey(
                blank=True,
                help_text="Pour une dépense de main d'œuvre : le personnel enregistré sur ce chantier concerné par cette dépense",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="personnel.personnel",
                verbose_name="Personnel concerné",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(verbose_name="Désignation"),
        ),
    ]
