# Generated by Django 5.2.17 on 2026-09-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_avenant_payrolllist_payrolllistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="recipient",
            field=models.CharField(
                blank=True,
                help_text="Qui a reçu ce paiement (fournisseur, ouvrier, tiers...) — pour la traçabilité, pas forcément une fiche du système.",
                max_length=255,
                verbose_name="Bénéficiaire",
            ),
        ),
    ]
