# Generated by Django 5.2.17 on 2026-09-22 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_salarypayment"),
        ("projects", "0005_progressphoto_progresscomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="caisse",
            name="manual_site_entry",
            field=models.BooleanField(
                default=False,
                help_text="Pour une caisse qui sert aussi des clients externes (ex : location de la bétonnière) : sur cette caisse, le formulaire de mouvement demande un chantier/client en texte libre au lieu d'imposer un chantier interne.",
                verbose_name="Chantier saisi manuellement (clients externes)",
            ),
        ),
        migrations.AddField(
            model_name="caissetransaction",
            name="external_site_label",
            field=models.CharField(
                blank=True,
                help_text="Pour les caisses à clients externes : nom du chantier ou du client tel que communiqué, sans lien vers un chantier interne.",
                max_length=255,
                verbose_name="Chantier / Client (texte libre)",
            ),
        ),
        migrations.AddField(
            model_name="caissetransaction",
            name="recipient",
            field=models.CharField(
                blank=True,
                help_text="Qui a reçu ou remis ce montant — pour la traçabilité, pas forcément une fiche du système.",
                max_length=255,
                verbose_name="Bénéficiaire",
            ),
        ),
        migrations.AlterField(
            model_name="caissetransaction",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Chantier interne. Laisser vide et utiliser le champ texte libre pour un client externe (ex : Bétonnière).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caisse_transactions",
                to="projects.site",
                verbose_name="Chantier",
            ),
        ),
        migrations.CreateModel(
            name="CaisseTransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Caisse Transaction Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="caissetransaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="finance.caissetransactioncategory",
                verbose_name="Catégorie",
            ),
        ),
    ]
