# Generated by Django 5.2.17 on 2026-09-22 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_seed_caisse_transaction_categories"),
        ("personnel", "0007_personnel_payroll_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrolllistitem",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="La convention (SiteAssignment) précise que ce paiement couvre — permet le plafond par convention et le rapprochement déjà payé/reste à payer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payroll_items",
                to="personnel.siteassignment",
                verbose_name="Convention / affectation",
            ),
        ),
    ]
