# Generated by Django 5.2.17 on 2026-09-24 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_salary_payments_forward(apps, schema_editor):
    """Fold each existing (flat, immediately-disbursed) SalaryPayment row
    into its own single-item SalaryPaymentList, status PAYEE, so the
    "Ingénieurs & Staff" workflow switches to brouillon/soumise/payée
    without losing or re-booking any already-paid salary. The caisse
    outflow itself was already recorded by the old SalaryPayment.disburse()
    at creation time — this only re-shapes the record, it doesn't touch
    CaisseTransaction."""
    SalaryPayment = apps.get_model('finance', 'SalaryPayment')
    SalaryPaymentList = apps.get_model('finance', 'SalaryPaymentList')
    SalaryPaymentItem = apps.get_model('finance', 'SalaryPaymentItem')
    for payment in SalaryPayment.objects.select_related('personnel').all():
        salary_list = SalaryPaymentList.objects.create(
            cabinet=payment.personnel.cabinet,
            prepared_by=payment.paid_by,
            status='PAYEE',
            notes=payment.notes,
            caisse=payment.caisse,
            submitted_at=payment.updated_at,
            paid_at=payment.updated_at,
            paid_by=payment.paid_by,
        )
        SalaryPaymentItem.objects.create(
            salary_payment_list=salary_list,
            personnel=payment.personnel,
            period=payment.period,
            amount=payment.amount,
        )


def migrate_salary_payments_backward(apps, schema_editor):
    """Best-effort reverse for migrate_salary_payments_forward: flattens
    every SalaryPaymentItem back into a SalaryPayment row (losing the
    brouillon/soumise distinction — a reversed SOUMISE/BROUILLON list has
    no equivalent in the old flat model, so its items are skipped)."""
    SalaryPayment = apps.get_model('finance', 'SalaryPayment')
    SalaryPaymentItem = apps.get_model('finance', 'SalaryPaymentItem')
    for item in SalaryPaymentItem.objects.select_related('salary_payment_list').all():
        salary_list = item.salary_payment_list
        if salary_list.status != 'PAYEE' or not salary_list.caisse_id:
            continue
        SalaryPayment.objects.create(
            personnel=item.personnel,
            period=item.period,
            amount=item.amount,
            caisse_id=salary_list.caisse_id,
            notes=item.notes or salary_list.notes,
            paid_by=salary_list.paid_by,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_usercabinetrole_role"),
        ("finance", "0015_seed_payroll_caisse_categories"),
        ("personnel", "0008_alter_personnel_payroll_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryPaymentList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("SOUMISE", "Soumise à la caisse"),
                            ("PAYEE", "Payée"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payment_lists",
                        to="accounts.cabinet",
                    ),
                ),
                (
                    "caisse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_payment_lists",
                        to="finance.caisse",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_payment_lists_disbursed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_payment_lists_prepared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalaryPaymentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="Mois concerné par ce paiement, ex : 2026-09",
                        max_length=7,
                        verbose_name="Période (AAAA-MM)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payment_items",
                        to="personnel.personnel",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "salary_payment_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.salarypaymentlist",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "personnel__last_name"],
                "unique_together": {("personnel", "period")},
            },
        ),
        migrations.RunPython(
            migrate_salary_payments_forward, migrate_salary_payments_backward,
        ),
        migrations.DeleteModel(
            name="SalaryPayment",
        ),
    ]
