# Generated by Django 5.2.17 on 2026-10-06 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_salarypaymentlist_salarypaymentitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="caisse",
            name="responsible_cashier",
            field=models.ForeignKey(
                blank=True,
                help_text="Le caissier (ou le comptable faisant office de caissier, dans un cabinet à effectif réduit) responsable de cette caisse — added 2026-10-06, permission table update. Avec recorded_by sur CaisseTransaction, détermine qui peut modifier un mouvement existant : la personne responsable de la caisse, ou celle qui l'a enregistré.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_caisses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Caissier responsable",
            ),
        ),
    ]
