# Generated by Django 5.2.17 on 2026-10-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0018_caissetransactionmaterialline"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrolllistitem",
            name="overage_note",
            field=models.TextField(
                blank=True,
                help_text="Obligatoire uniquement quand ce paiement dépasse la convention actuelle d'un Chef de corps (voir clean()) — expose le dépassement au DG et au bureau technique via le rapport « Dépassements de convention ».",
                verbose_name="Note de dépassement",
            ),
        ),
    ]
