# Generated by Django 5.2.17 on 2026-09-17 22:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_user_must_change_password"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceLibraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identifiant court, ex. MO-001, MAT-012",
                        max_length=30,
                        verbose_name="Code",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("LABOR", "Main d'œuvre"),
                            ("MATERIAL", "Matériau"),
                            ("EQUIPMENT", "Matériel"),
                            ("SERVICE", "Prestation"),
                            ("WORK_ITEM", "Ouvrage (composite)"),
                        ],
                        default="WORK_ITEM",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="ex. m², m³, kg, forfait, jour",
                        max_length=50,
                        verbose_name="Unité",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Prix unitaire"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cabinet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_library_items",
                        to="accounts.cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de la bibliothèque de prix",
                "verbose_name_plural": "Bibliothèque de prix",
                "ordering": ["code"],
                "unique_together": {("cabinet", "code")},
            },
        ),
    ]
