# Generated by Django 5.2.17 on 2026-10-07 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_cabinet_material_variance_orange_threshold_pct_and_more"),
        ("materials", "0009_materialrequestitem_phase"),
        ("pricing", "0002_dqe_dqeline"),
        ("projects", "0007_projectphase_parent_phase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dqeline",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                help_text="L'étape (ou sous-étape) du chantier concernée par cette ligne — nécessaire pour comparer les demandes de matériaux à ce poste du devis étape par étape.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dqe_lines",
                to="projects.projectphase",
                verbose_name="Étape",
            ),
        ),
        migrations.AddField(
            model_name="pricelibraryitem",
            name="material",
            field=models.ForeignKey(
                blank=True,
                help_text="Pour un article de type « Matériau » : le matériau élémentaire correspondant, utilisé pour comparer directement ce poste du DQE aux demandes de matériaux (sans passer par une explosion de ratios).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_library_items",
                to="materials.material",
                verbose_name="Matériau",
            ),
        ),
        migrations.AddField(
            model_name="pricelibraryitem",
            name="work_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BETON", "Béton (toutes classes de dosage)"),
                    ("ACIER", "Acier / armatures"),
                    ("COFFRAGE", "Coffrage"),
                    ("MACONNERIE", "Maçonnerie"),
                    ("AUTRE", "Autre ouvrage"),
                ],
                help_text="Obligatoire pour un article de type « Ouvrage (composite) » — indique à quelle nomenclature de ratios (ciment, acier, sable...) ce poste doit être rattaché pour l'explosion en matériaux élémentaires.",
                max_length=20,
                verbose_name="Catégorie d'ouvrage",
            ),
        ),
        migrations.CreateModel(
            name="MaterialConsumptionRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "work_category",
                    models.CharField(
                        choices=[
                            ("BETON", "Béton (toutes classes de dosage)"),
                            ("ACIER", "Acier / armatures"),
                            ("COFFRAGE", "Coffrage"),
                            ("MACONNERIE", "Maçonnerie"),
                            ("AUTRE", "Autre ouvrage"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie d'ouvrage",
                    ),
                ),
                (
                    "ratio",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantité du matériau par unité de l'ouvrage, ex. 7 (sacs de ciment) par m³ de béton",
                        max_digits=12,
                        verbose_name="Ratio",
                    ),
                ),
                (
                    "ratio_unit",
                    models.CharField(
                        help_text="ex. sacs/m³, kg/m³",
                        max_length=50,
                        verbose_name="Unité du ratio",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "cabinet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laisser vide pour un ratio par défaut (applicable à tous les cabinets, sauf override).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_consumption_ratios",
                        to="accounts.cabinet",
                        verbose_name="Cabinet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_ratios",
                        to="materials.material",
                        verbose_name="Matériau",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ratio de consommation matière",
                "verbose_name_plural": "Ratios de consommation matière",
                "ordering": ["work_category", "material__name"],
                "unique_together": {("cabinet", "work_category", "material")},
            },
        ),
    ]
