# Generated by Django 6.0.3 on 2026-04-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_remove_materialrequest_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('ORDERED', 'Commandé'), ('DELIVERED', 'Livré')], default='PENDING', max_length=20),
        ),
    ]
