# Generated by Django 5.2.17 on 2026-09-21 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_materialrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="material_name",
            field=models.CharField(
                blank=True,
                help_text="À utiliser si le matériel n'est pas dans le catalogue",
                max_length=255,
                verbose_name="Nom du matériel",
            ),
        ),
        migrations.AlterField(
            model_name="materialrequestitem",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_items",
                to="materials.material",
            ),
        ),
    ]
