# Generated by Django 5.2.17 on 2026-10-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_alter_materialrequest_status"),
        ("projects", "0007_projectphase_parent_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequestitem",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                help_text="L'étape (ou sous-étape) du chantier à laquelle ce matériau est destiné — permet de comparer la demande aux estimations du devis pour cette étape.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_request_items",
                to="projects.projectphase",
                verbose_name="Étape",
            ),
        ),
    ]
