# Generated by Django 5.2.17 on 2026-10-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_materialrequestitem_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialrequest",
            name="overage_justification",
            field=models.TextField(
                blank=True,
                help_text="Obligatoire uniquement quand au moins un article de cette demande dépasse largement l'estimation du devis pour son étape (voir authorize()) — expose le dépassement au DG et au bureau technique via le rapport de conformité devis.",
                verbose_name="Justification de dépassement",
            ),
        ),
    ]
