# Generated by Django 5.2.17 on 2026-10-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_materialrequest_overage_justification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("VALIDATED", "Validé (ancien statut)"),
                    ("APPROVED", "Approuvé"),
                    ("REJECTED", "Rejeté"),
                    ("ORDERED", "Commandé"),
                    ("DELIVERED", "Livré"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
