# Generated by Django 5.2.10 on 2026-01-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cabinet_unique_id_usercabinetrole_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercabinetrole',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
