# Generated by Django 6.0.3 on 2026-04-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usercabinetrole_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinetrole',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Directeur de Cabinet'), ('CHIEF_ENGINEER', 'Chef des Ingénieurs'), ('ENGINEER', 'Ingénieur'), ('ACCOUNTANT', 'Comptable'), ('CASHIER', 'Caissier'), ('WORKER', 'Ouvrier')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usercabinetrole',
            name='status',
            field=models.CharField(choices=[('PENDING', "En attente d'approbation"), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20),
        ),
    ]
