# Generated by Django 6.0.4 on 2026-04-13 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usercabinetrole_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetContextLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SWITCH', 'Switch to Cabinet'), ('CLEAR', 'Clear to All Cabinets')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_logs', to='accounts.cabinet')),
                ('switched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_context_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
