# Generated by Django 5.2.17 on 2026-09-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_usercabinetrole_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercabinetrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("DIRECTOR", "Directeur de Cabinet"),
                    ("DIRECTEUR_TECHNIQUE", "Directeur Technique"),
                    ("DIRECTEUR_GENERAL", "Directeur Général"),
                    ("CHIEF_ENGINEER", "Chef des Ingénieurs"),
                    ("ENGINEER", "Ingénieur"),
                    ("FINANCIER", "Financier"),
                    ("ACCOUNTANT", "Comptable"),
                    ("CASHIER", "Caissier"),
                    ("MAGASINIER", "Magasinier"),
                    ("WORKER", "Ouvrier"),
                ],
                max_length=50,
            ),
        ),
    ]
