# Generated by Django 5.2.17 on 2026-10-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_usercabinetrole_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabinet",
            name="material_variance_orange_threshold_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="Au-delà de ce pourcentage de la quantité budgétée (devis/DQE), une comparaison matériau passe à l'orange (« à surveiller »). 100 = la demande cumulée atteint exactement l'estimation initiale.",
                max_digits=6,
                verbose_name="Seuil orange (% du devis)",
            ),
        ),
        migrations.AddField(
            model_name="cabinet",
            name="material_variance_red_threshold_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=120,
                help_text="Au-delà de ce pourcentage de la quantité budgétée, une comparaison matériau passe au rouge (« dépassement ») et exige une justification à l'autorisation.",
                max_digits=6,
                verbose_name="Seuil rouge (% du devis)",
            ),
        ),
    ]
