# Generated by Django 5.2.17 on 2026-10-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_cabinet_material_variance_orange_threshold_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabinet",
            name="rebar_density_kg_per_m3",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="Quantité d'acier (kg) estimée par m³ de béton structurel (poutres, colonnes, dalles) — utilisée pour chiffrer l'acier des niveaux d'un chantier (Site.estimated_rebar_kg) quand aucun ratio d'armature détaillé n'est saisi poste par poste. 100 kg/m³ est un ordre de grandeur courant pour du bâtiment courant (un ouvrage très ferraillé — parking, voile de soutènement — en demande davantage) ; ajustable par cabinet.",
                max_digits=8,
                verbose_name="Densité d'armature par défaut (kg/m³)",
            ),
        ),
    ]
