# Generated by Django 6.0.3 on 2026-04-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_contract_unique_id_invoice_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('PAID', 'Payé'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Virement bancaire'), ('CHECK', 'Chèque'), ('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money')], max_length=50),
        ),
    ]
