# Generated by Django 5.2.17 on 2026-09-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0004_devis_devisline_situationtravaux_situationline"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo/scan d'un devis papier — alternative à la saisie manuelle des lignes ci-dessous",
                null=True,
                upload_to="devis/photos/",
                verbose_name="Photo du devis",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="proof_of_payment",
            field=models.FileField(
                blank=True,
                help_text="Reçu, capture de virement ou autre justificatif — facultatif",
                null=True,
                upload_to="payments/proofs/",
                verbose_name="Preuve de paiement",
            ),
        ),
    ]
