# Generated by Django 5.2.17 on 2026-09-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0005_devis_photo_payment_proof_of_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="avenant_debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Dépenses au-delà du budget initial, autorisées par avenant : dette du client en plus du prix du contrat.",
                max_digits=14,
                verbose_name="Dette avenants",
            ),
        ),
    ]
