# Generated by Django 5.2.17 on 2026-10-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_dqeline_phase_pricelibraryitem_material_and_more"),
        ("revenue", "0006_contract_avenant_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="source_dqe",
            field=models.ForeignKey(
                blank=True,
                help_text="Le DQE détaillé (quantités/matériaux par étape) dont ce devis est issu — sert de référence pour comparer les demandes de matériaux aux estimations initiales, étape par étape.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis_set",
                to="pricing.dqe",
                verbose_name="DQE source",
            ),
        ),
    ]
