# Generated by Django 5.2.17 on 2026-09-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="caisse",
            field=models.CharField(
                choices=[
                    ("PRINCIPALE", "Caisse principale"),
                    ("SECONDAIRE", "Caisse secondaire"),
                ],
                default="PRINCIPALE",
                help_text="Caisse ayant financé cet achat — utilisée pour tous les chantiers, sert uniquement au filtrage des rapports",
                max_length=20,
                verbose_name="Caisse",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="facture",
            field=models.FileField(
                blank=True,
                help_text="Justificatif (facture/reçu) lié à ce mouvement — facultatif",
                null=True,
                upload_to="stock_movements/factures/",
                verbose_name="Facture",
            ),
        ),
    ]
