# Generated by Django 5.2.17 on 2026-09-21 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0003_purchaseorder_entered_at_and_more"),
        ("projects", "0004_projectphase_closed_at_projectphase_closed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="is_transfer_source",
            field=models.BooleanField(
                default=False,
                help_text="Pour un mouvement de type Transfert : True côté origine (sortie), False côté destination (entrée).",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="motif",
            field=models.CharField(
                blank=True,
                help_text="Raison du mouvement",
                max_length=255,
                verbose_name="Motif",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                help_text="Étape du chantier concernée (facultatif)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="projects.projectphase",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="transfer_pair",
            field=models.OneToOneField(
                blank=True,
                help_text="L'autre moitié de ce transfert (origine <-> destination).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_pair_reverse",
                to="procurement.stockmovement",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("IN", "Entrée"),
                    ("OUT", "Sortie"),
                    ("ADJUSTMENT", "Ajustement"),
                    ("TRANSFER", "Transfert"),
                ],
                max_length=20,
            ),
        ),
    ]
